CREATE DATABASE QLHH
ON PRIMARY (
    NAME = QLHH_Data,
    FILENAME = 'E:\DevMaster\DATABASE\QLHH_Data.mdf',  -- Đường dẫn tới tệp dữ liệu
    SIZE = 50MB,
    FILEGROWTH = 10MB,
    MAXSIZE = 200MB
)
LOG ON (
    NAME = QLHH_Log,
    FILENAME = 'E:\DevMaster\DATABASE\QLHH_Log.ldf',  -- Đường dẫn tới tệp nhật ký
    SIZE = 10MB,
    FILEGROWTH = 5MB
);
go
CREATE DATABASE QLBH
ON PRIMARY (
    NAME = QLHH_Data,
    FILENAME = 'E:\DevMaster\DATABASE\QLBH_Data.mdf',  -- Đường dẫn tới tệp dữ liệu
    SIZE = 50MB,
    FILEGROWTH = 10MB,
    MAXSIZE = 200MB
)
LOG ON (
    NAME = QLHH_Log,
    FILENAME = 'E:\DevMaster\DATABASE\QLBH_Log.ldf',  -- Đường dẫn tới tệp nhật ký
    SIZE = 10MB,
    FILEGROWTH = 5MB
);

go
use  QLBH
go

CREATE TABLE VATTU(
MaVTu CHAR(4) PRIMARY KEY,
TenVTu VARCHAR(100) NOT NULL UNIQUE,
DvTinh VARCHAR(4) NULL DEFAULT(''),
PhanTram REAL CHECK(0<= PhanTram AND PhanTram<=100)
)

CREATE TABLE NHACC(
MaNhaCc CHAR(3) PRIMARY KEY,
TenNhaCc VARCHAR (100) NOT NULL,
DiaChi VARCHAR(200) NOT NULL
)

CREATE TABLE DONDH(
SoDH CHAR(4) PRIMARY KEY,
NgayDH DATETIME DEFAULT(GETDATE()),
MaNhaCc cHAR(3) NOT NULL constraint FK_MaNhaCc FOREIGN KEY REFERENCES NHACC(MaNhaCc)
)

CREATE TABLE CTDONDH(
SoDH CHAR(4) NOT NULL,
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES VATTU(MaVTu),
SlDat INT NOT NULL CHECK(SlDat>0)
)

CREATE TABLE PNHAP(
SoPn CHAR(4) PRIMARY KEY,
NgayNhap DATETIME NOT NULL DEFAULT(GETDATE()),--MẶC ĐỊNH NGÀY HIỆN HÀNH
SoDh CHAR(4) NOT NULL--GIÁ TRỊ TỒN TẠI TRONG SỐ SoDh CỦA BẢNG DONDH
)

CREATE TABLE CTPNHAP(
SoPn CHAR(4) constraint FK_SoPn FOREIGN KEY REFERENCES PNHAP(SoPn),
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES VATTU(MaVTu),   --GIÁ TRỊ PHẢI TỒN TẠI TRONG CỘT MaVTu TRONG BẢNG VATTU
SlNhap INT NOT NULL CHECK(SlNhap>0),-->0
DgNhap MONEY NOT NULL CHECK(DgNhap>0)-->0

)

CREATE TABLE PXUAT(
SoPx CHAR(4) PRIMARY KEY,
NgayXuat DATETIME NOT NULL DEFAULT(GETDATE()),--MẶC ĐỊNH NGÀY HIỆN HÀNH
TenKh VARCHAR(100) NOT NULL
)

CREATE TABLE CTPXUAT(
SoPx CHAR(4)  constraint FK_SoPx FOREIGN KEY REFERENCES PXUAT(SoPx),
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES VATTU(MaVTu)  , --GIÁ TRỊ PHẢI TỒN TẠI TRONG CỘT MaVTu TRONG BẢNG VATTU
SlXuat INT NOT NULL CHECK(SlXuat>0),-->0
DgXuat MONEY NOT NULL CHECK(DgXuat>0)-->0

)

CREATE TABLE TONKHO (
NamThang CHAR (6) PRIMARY KEY,
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES VATTU(MaVTu),
SLDau INT NOT NULL CHECK(SLDau>0),-->0
TongSLN INT NOT NULL CHECK(TongSLN >0),-->0
TongSLX INT NOT NULL CHECK(TongSLX >0),-->0
SLCuoi INT AS (SLDau + TongSLN - TongSLX) -- = SLDau+TongSLN-TongSLX 
)
