CREATE DATABASE QLHH
ON PRIMARY (
    NAME = QLHH_Data,
    FILENAME = 'E:\DevMaster\DATABASE\QLHH_Data.mdf',  -- Đường dẫn tới tệp dữ liệu
    SIZE = 50MB,
    FILEGROWTH = 10MB,
    MAXSIZE = 200MB
)
LOG ON (
    NAME = QLHH_Log,
    FILENAME = 'E:\DevMaster\DATABASE\QLHH_Log.ldf',  -- Đường dẫn tới tệp nhật ký
    SIZE = 10MB,
    FILEGROWTH = 5MB
);
go
CREATE DATABASE QLBH
ON PRIMARY (
    NAME = QLHH_Data,
    FILENAME = 'E:\DevMaster\DATABASE\QLBH_Data.mdf',  -- Đường dẫn tới tệp dữ liệu
    SIZE = 50MB,
    FILEGROWTH = 10MB,
    MAXSIZE = 200MB
)
LOG ON (
    NAME = QLHH_Log,
    FILENAME = 'E:\DevMaster\DATABASE\QLBH_Log.ldf',  -- Đường dẫn tới tệp nhật ký
    SIZE = 10MB,
    FILEGROWTH = 5MB
);

go

CREATE TABLE MaVTu(
MaVTu CHAR(4) PRIMARY KEY,
TenVTu VARCHAR(100) NOT NULL UNIQUE,
DvTinh VARCHAR(4) NULL,
PhanTram REAL,
)
GO
CREATE TABLE NHACC(
MaNhaCc CHAR(3) PRIMARY KEY,
TenNhaCc VARCHAR (100) NOT NULL,
DiaChi VARCHAR(200) NOT NULL,
)
GO
CREATE TABLE DONDH(
SoDH CHAR(4) PRIMARY KEY,
NgayDH DATETIME DEFAULT(GETDATE()),
MaNhaCc cHAR(3) NOT NULL,
)
GO
CREATE TABLE CTDONDH(
SoDH CHAR(4) NOT NULL,
MaVTu CHAR(4) NOT NULL,
SlDat INT NOT NULL,
)
GO
CREATE TABLE PNHAP(
SoPn CHAR(4) NOT NULL,
NgayNhap DATETIME NOT NULL DEFAULT(GETDATE()),--MẶC ĐỊNH NGÀY HIỆN HÀNH
SoDh CHAR(4) NOT NULL,--GIÁ TRỊ TỒN TẠI TRONG SỐ SoDh CỦA BẢNG DONDH
)
GO 
CREATE TABLE CTPNHAP(
SoPn CHAR(4)  PRIMARY KEY,
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES MaVTu(MaVTu),   --GIÁ TRỊ PHẢI TỒN TẠI TRONG CỘT MaVTu TRONG BẢNG VATTU
SlNhap INT NOT NULL,-->0
DgNhap MONEY NOT NULL,-->0

)
GO 
CREATE TABLE PXUAT(
SoPx CHAR(4) PRIMARY KEY,
NgayXuat DATETIME NOT NULL DEFAULT(GETDATE()),--MẶC ĐỊNH NGÀY HIỆN HÀNH
TenKh VARCHAR(100) NOT NULL
)
GO 
CREATE TABLE CTPXUAT(
SoPx CHAR(4)  PRIMARY KEY,
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES MaVTu(MaVTu)  , --GIÁ TRỊ PHẢI TỒN TẠI TRONG CỘT MaVTu TRONG BẢNG VATTU
SlXuat INT NOT NULL,-->0
DgXuat MONEY NOT NULL,-->0

)
GO CREATE TABLE TONKHO (
NamThang CHAR (6) PRIMARY KEY,
MaVTu CHAR(4) constraint FK_MaVTu FOREIGN KEY REFERENCES MaVTu(MaVTu),
SLDau INT NOT NULL,-->0
TongSLN INT NOT NULL,-->0
TongSLX INT NOT NULL,-->0
SLCuoi INT -- = SLDau+TongSLN-TongSLX 
)